Add friends likes
argoneen1/java-filmorate pull request #5
Opened 2022-07-17 18:36 UTC by argoneen1

2022-07-18 07:51 UTC, EugeneLenkevich requested changes
Привет, , спасибо за PR

В целом все супер, очень интересная реализация контроллера через наследование :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-07-18 07:51 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return storage.get().stream()
В данном случае мы в сервис вытаскиваем детали реализации стореджа, проводим сортировку и отборку данных. Это скорее обязанности стореджа.
А не лучше ли в сторедже создать соответствующий поисковый метод и всю логику поиска поместить в него? 
Так мы спрячем детали реализации. Допустим, потом у нас появится база данных, нам будет достаточно только переписать метод стореджа, а так продеться искать подобный код по всем сервисам :)

Аналогичная ситуация, кстати, и в соседних методах

2022-07-18 07:51 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            log.warn( Film.getElemName() + " with id " + elem.getId() + " already was included.");
В логгере лучше использовать плейсхолдеры. Это еще и более оптимально так как такие выражения не будут вычисляться вовсе в случае если не включен соответствующий уровень логирования. В случае же с конкатенацией выражения будут выполняться всегда :)

log.warn( " {} with id  {} was included.", Film.getElemName(), elem.getId());

К тому же в других местах итак плейсхолдеры ;)

2022-07-24 17:29 UTC, argoneen1 commented
setLike и deleteLike не перенёс, ибо подумал, что связывать стореджи между собой нехорошо, лучше оставить связь на уровне сервис.

2022-07-24 17:43 UTC, EugeneLenkevich approved these changes
Все супер, спасибо!

2022-08-19 13:33 UTC, merged